#!/usr/bin/env python3
"""
audit_no_placeholder.py
=======================
Scans all text/latex files in the repo for placeholders like TODO, TBD, XX.X, [INSERT].
Also generates docs/TRACEABILITY_MAP.md.

Per Bước 11 of the SOTA improvement plan.
"""

import os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(ROOT, "docs")
PAPER = os.path.join(ROOT, "paper")
os.makedirs(DOCS, exist_ok=True)

PLACEHOLDERS = [r"TODO", r"TBD", r"XX\.X", r"\[INSERT\]", r"\?\?\?"]

def scan_dir(directory):
    found = False
    for root, _, files in os.walk(directory):
        for f in files:
            if not (f.endswith(".md") or f.endswith(".tex") or f.endswith(".txt")):
                continue
            if "CHANGELOG" in f or "TRACEABILITY" in f or "audit_no_placeholder" in f:
                continue
            path = os.path.join(root, f)
            with open(path, "r", encoding="utf-8", errors="ignore") as file:
                lines = file.readlines()
                for i, line in enumerate(lines):
                    for p in PLACEHOLDERS:
                        if re.search(p, line, re.IGNORECASE):
                            print(f"Placeholder '{p}' found in {os.path.relpath(path, ROOT)}:{i+1}")
                            print(f"  > {line.strip()}")
                            found = True
    return found

def generate_traceability():
    content = """# Traceability Map for SOTA Metrics

This document maps every metric claimed in the paper to its corresponding verified log file.

## Account-Level Classification (Table II)
- **UnifiedTMIL v1 (Baseline)**
  - ID-F1: `results/clean_results.json` -> `account_level.id_f1.mean`
  - Hard-AUC: `results/clean_results.json` -> `account_level.hard_auc.mean`
  - X-AUC: `results/clean_results.json` -> `account_level.x_auc.mean`
- **UnifiedTMIL v2 (SOTA)**
  - ID-F1: `results/unifiedtmil_v2_sota_results.json` -> `configs.v2_best.in_domain.f1.mean`
  - Hard-AUC: `results/unifiedtmil_v2_sota_results.json` -> `configs.v2_best.hard_auc.mean`
  - X-AUC: `results/unifiedtmil_v2_sota_results.json` -> `configs.v2_best.cross_domain.auc`
  - *Note: Final paper numbers require full 5-seed GPU run.*

## Transaction-Level Localization (Table III)
- **UnifiedTMIL v1 (GBM Fusion)**
  - Hit@1/MRR: `results/clean_results.json` -> `transaction_level.content_aware_fusion`
- **UnifiedTMIL v2 (SOTA)**
  - *PENDING: requires GBM fusion run with v2 attention scores.*

## Architecture Cost (Table V)
- All numbers generated by `scripts/architecture_cost.py`
- Saved in `results/architecture_cost.json`
- Hardware measured on: CPU (x86_64), 6 cores

## Statistical Tests
- All p-values generated by `scripts/statistical_test.py`
- Saved in `results/statistical_tests.json`
"""
    path = os.path.join(DOCS, "TRACEABILITY_MAP.md")
    with open(path, "w") as f:
        f.write(content)
    print(f"Generated {path}")

def main():
    print("=" * 60)
    print("Auditing for Placeholders")
    print("=" * 60)
    
    found_docs = scan_dir(DOCS)
    found_paper = scan_dir(PAPER)
    
    if found_docs or found_paper:
        print("\nWARNING: Placeholders found. Do not compile final PDF until resolved.")
    else:
        print("\nSUCCESS: No placeholders found in scanned files.")
        
    print("\n" + "=" * 60)
    print("Generating Traceability Map")
    print("=" * 60)
    generate_traceability()

if __name__ == "__main__":
    main()
